#!/usr/bin/env bash
# Reads secrets.env and writes gitignored native config for Google Maps API keys.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

ENV_FILE="${ROOT}/secrets.env"
EXAMPLE="${ROOT}/secrets.env.example"

if [[ ! -f "$ENV_FILE" ]]; then
  echo "Missing ${ENV_FILE}"
  echo "  cp secrets.env.example secrets.env"
  echo "  # edit secrets.env with your Maps API key(s)"
  exit 1
fi

# shellcheck disable=SC1090
set -a
source "$ENV_FILE"
set +a

resolve_key() {
  local platform="$1"
  local generic="${GOOGLE_MAPS_API_KEY:-}"
  local ios="${GOOGLE_MAPS_API_KEY_IOS:-}"
  local android="${GOOGLE_MAPS_API_KEY_ANDROID:-}"

  case "$platform" in
    ios)
      if [[ -n "$ios" ]]; then echo "$ios"
      elif [[ -n "$generic" ]]; then echo "$generic"
      else echo ""; fi
      ;;
    android)
      if [[ -n "$android" ]]; then echo "$android"
      elif [[ -n "$generic" ]]; then echo "$generic"
      else echo ""; fi
      ;;
    *) echo "" ;;
  esac
}

IOS_KEY="$(resolve_key ios)"
ANDROID_KEY="$(resolve_key android)"

if [[ -z "$IOS_KEY" && -z "$ANDROID_KEY" ]]; then
  echo "No Maps API key set in secrets.env."
  echo "Set GOOGLE_MAPS_API_KEY or GOOGLE_MAPS_API_KEY_IOS / GOOGLE_MAPS_API_KEY_ANDROID."
  exit 1
fi

# --- iOS: MapsSecrets.xcconfig (included by all Flutter *.xcconfig) ---
IOS_XCCONFIG="${ROOT}/ios/Flutter/MapsSecrets.xcconfig"
if [[ -n "$IOS_KEY" ]]; then
  cat >"$IOS_XCCONFIG" <<EOF
// Generated by scripts/apply_maps_secrets.sh — do not edit.
GOOGLE_MAPS_API_KEY=${IOS_KEY}
EOF
  echo "Wrote ios/Flutter/MapsSecrets.xcconfig"
else
  echo "Skipping iOS (no GOOGLE_MAPS_API_KEY_IOS / GOOGLE_MAPS_API_KEY)"
fi

# --- Android: maps-secrets.properties ---
ANDROID_PROPS="${ROOT}/android/maps-secrets.properties"
if [[ -n "$ANDROID_KEY" ]]; then
  cat >"$ANDROID_PROPS" <<EOF
# Generated by scripts/apply_maps_secrets.sh — do not edit.
GOOGLE_MAPS_API_KEY=${ANDROID_KEY}
EOF
  echo "Wrote android/maps-secrets.properties"
else
  echo "Skipping Android (no GOOGLE_MAPS_API_KEY_ANDROID / GOOGLE_MAPS_API_KEY)"
fi

echo ""
echo "Done. Rebuild the app (flutter run / Xcode), not hot reload."
